
spring:
  application:
    name: eureka
server:
  port: 30000

eureka:
  server:
    enable-self-preservation: true
  client:
    fetch-registry: false
    register-with-eureka: false

    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    registry-fetch-interval-seconds: 5


